### ISSUE TITLE
Week 4: Morning Session Code Review

### ISSUE THREAD

**Issue by DammyShittu** [rpire/microverse-portfolio#16]
**Hi Ruben,**

*Kudos to you on the great work done so far in building out your portfolio 👏 . The project looks really awesome.*

# Suggestions ♻️ 

- As seen in the JS file, validation was carried out on all input and textarea fields. This was also done in the HTML file using the 'required' attribute. Kindly check to see how validation can only be used in either HTML or JavaScript. This can be done by removing the 'required' attribute in HTML.

- Kindly add some padding in the input and textarea fields so the user input would not start directly from the left border.

### Generally, the project looks great. Well done Ruben. 👍 

# Happy Coding. 🎉

**Comment by rpire** [comment]
Hello @DammyShittu 🖐

## Thank you for reviewing my work. 🤓

I liked your observations and I totally agree with them. I will make sure to complete the requested changes and merge them.

Thanks again, Cheers and Happy coding! 🚀
